apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    # Parameters for Platform prometheus
    prometheusK8s:
      # retention: 15d
      # retentionSize: 90GB
      # volumeClaimTemplate:
      #   spec:
      #     resources:
      #       requests:
      #         storage: 100Gi