apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    # Parameters for default prometheus
    prometheusK8s:
      # retention: 15d
      retention: 24h
      # volumeClaimTemplate:
      #   spec:
      #     resources:
      #       requests:
      #         storage: 5Gi
    alertmanagerMain:
      enableUserAlertmanagerConfig: true