apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus: 
      retention: 1h 
      resources:
        requests:
          cpu: 100m 
          memory: 200Mi
        limits:
          cpu: "1" 
          memory: 1Gi
      # volumeClaimTemplate:
      #   spec:
      #     resources:
      #       requests:
      #         storage: 5Gi
    thanosRuler:
      retention: 1d
      resources:
        requests:
          cpu: 50m 
          memory: 100Mi
        limits:
          cpu: "1" 
          memory: 1Gi
      # volumeClaimTemplate:
      #   spec:
      #     resources:
      #       requests:
      #         storage: 3Gi