apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      # retention: 1d
      # retentionSize: 4GB
      # resources:
      #   requests:
      #     cpu: 6m
      #     memory: 30Mi
      # volumeClaimTemplate:
      #   spec:
      #     resources:
      #       requests:
      #         storage: 5Gi
    