apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: users-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: User
  name: user2
---
# This role is needed to create ServiceMonitor and PrometheusRule. Alternatively if Prometheus operator was installed via OperatorHub on the cluster anywhere, it's part of the default view/edit/admin ClusterRoles already.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit
subjects:
- kind: User
  name: user2
---
# This is needed to create AlertmanagerConfig
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alert-routing-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alert-routing-edit
subjects:
- kind: User
  name: user2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operatorhub-users-team-b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregate-olm-view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: olm-installplan-approval
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - installplans
  verbs:
  - update
  - patch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: olm-installplan-approval
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: olm-installplan-approval
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user2