apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: users-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: User
  name: user2