apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-a

resources:
- ../../base/grafana/operator
- ../../base/sso/operator
- ../../base/amq/operator
- grafana-rolebinding.yaml
