apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-a

resources:
- namespace.yaml
- operator-group.yaml
- grafana-rolebinding.yaml
- ../../base/grafana/operator
- ../../base/sso/operator
