apiVersion: batch/v1
kind: Job
metadata:
  generateName: grafana-setup-
spec:
  parallelism: 1
  completions: 1
  suspend: false
  template:
    spec:
      serviceAccountName: grafana-thanos
      restartPolicy: Never
      containers:
        - name: setup-scripts
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli
          args:
            -  /script/sa-token-datasource-patch.sh
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /script
              name: script-cm
      volumes:
        - name: script-cm
          configMap:
            defaultMode: 0777
            name: setup-scripts
