apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  labels:
    app: grafana
  name: thanos
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: false
      jsonData:
        # customQueryParameters: namespace=mynamespace
        httpHeaderName1: Authorization
        # required for queries with $__rate_interval
        timeInterval: 15s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: >-
          Bearer [use grafana-thanos token]
      type: prometheus
      version: 1
      # Cluster scoped
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
      # Namespaced scoped - requires 'customQueryParameters: namespace=mynamespace' above
      # url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9092'
  name: grafana-datasource.yaml