apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - session-secret.yaml
  - ocp-injected-certs.yaml
  # - grafana-readonly.yaml
  - grafana-admin.yaml
  - grafana-datasource.yaml
  ## OCP 4.11
  - datasource-setup-job.yaml
  ## OCP 4.10
  # - datasource-setup-jobonly.yaml
configMapGenerator:
  - name: datasource-setup-script
    files:
      - sa-token-datasource-patch.sh
