apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- session-secret.yaml
- ocp-injected-certs.yaml
# - grafana-readonly.yaml
- grafana-admin.yaml
- grafana-datasource.yaml

  