apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- session-secret.yaml
- ocp-injected-certs.yaml
- grafana-admin.yaml
# - grafana-editor.yaml
# - grafana-readonly.yaml
- datasource.yaml

  