# In OpenShift 4.10 you can't use a separate Alertmanager for user-defined alerts, so we enable "alertmanagerMain" in this CM instead.
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s:
      retention: 24h
    alertmanagerMain:
      enableUserAlertmanagerConfig: true