apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
    thanosRuler:
      # retention: 24h
      # resources:
      #   requests:
      #     cpu: 1m
      #     memory: 21Mi
      # volumeClaimTemplate:
      #   spec:
      #     resources:
      #       requests:
      #         storage: 3Gi
    # We use this separate Alertmanager
    # to avoid sending user-defined alerts
    # through the default notification channels
    alertmanager:
      enabled: true
      enableAlertmanagerConfig: true
      # resources:
      #   requests:
      #     cpu: 4m
      #     memory: 40Mi
      # volumeClaimTemplate:
      #   spec:
      #     resources:
      #       requests:
      #         storage: 3Gi