apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      retention: 12h
      # resources:
      #   requests:
      #     cpu: 100m
      #     memory: 200Mi
      #   limits:
      #     cpu: "1"
      #     memory: 1Gi
    thanosRuler:
      retention: 1d
      # resources:
      #   requests:
      #     cpu: 50m
      #     memory: 100Mi
      #   limits:
      #     cpu: "1"
      #     memory: 1Gi
    # Instead of using the default alertmanagerMain in cluster-monitoring-config, we use this separate Alertmanager
    # to avoid sending user-defined alerts through the default notification route
    alertmanager:
      enabled: true
      enableAlertmanagerConfig: true
