{
 "title": "AMQ Broker",
 "description": "Dashboard for monitoring Apache Artemis",
 "tags": [ "apache artemis" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(artemis_connection_count, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(artemis_connection_count{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Started",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{pod=\"$instance\",  namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(jvm_memory_used_bytes{area=\"heap\", pod=\"$instance\", namespace=\"$namespace\"}[1m]))*100/sum(avg_over_time(jvm_memory_max_bytes{area=\"heap\", pod=\"$instance\", namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Global Max Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (broker) ( artemis_address_memory_usage_percentage{pod=\"$instance\", namespace=\"$namespace\"} )",
     "legendFormat": "{{ broker }}"
    }
   ]
  },
  {
   "title": "Message Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (broker)(artemis_message_count{pod='$instance',  namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (broker) ((rate(artemis_messages_added{pod=\"$instance\", namespace=\"$namespace\"}[1m])) + (rate(artemis_messages_acknowledged{pod=\"$instance\", namespace=\"$namespace\"}[1m])))"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (broker) ( artemis_disk_store_usage{pod=\"$instance\", namespace=\"$namespace\"} )",
     "legendFormat": "{{ broker }}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "core" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", pod=\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", pod=\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(pod:container_cpu_usage:sum{pod=\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\", pod=\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "Heap Max"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", pod=\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "Heap Usage"
    },
    {
     "expr": "sum by (broker) (artemis_address_memory_usage{pod=\"$instance\",  namespace=\"$namespace\"})",
     "legendFormat": "Global Max Usage"
    }
   ]
  },
  {
   "title": "Message Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (broker) (rate(artemis_messages_added{pod=\"$instance\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Producing"
    },
    {
     "expr": "sum by (broker) (rate(artemis_messages_acknowledged{pod=\"$instance\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Consuming"
    }
   ]
  },
  {
   "title": "Connections and Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (broker) ( artemis_connection_count{pod=\"$instance\",  namespace=\"$namespace\"} )",
     "legendFormat": "Connection Count"
    },
    {
     "expr": "sum by (address) ( topk (20, artemis_consumer_count{pod=\"$instance\",  namespace=\"$namespace\"} ) )",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Message Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (broker) (artemis_message_count{pod=\"$instance\",  namespace=\"$namespace\"})",
     "legendFormat": "{{ broker }}"
    },
    {
     "expr": "sum by (queue) ( topk (20, artemis_message_count{pod=\"$instance\",  namespace=\"$namespace\", address!~\"\\\\$.*|activemq\\\\.notifications\"} ) )",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Persistent Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (broker) (artemis_persistent_size{pod=\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "{{ broker }}"
    },
    {
     "expr": "sum by (queue) ( topk (20, artemis_persistent_size{pod=\"$instance\", namespace=\"$namespace\", address!~\"\\\\$.*|activemq\\\\.notifications\"} ) )",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Messages Produced",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) ( topk (20, rate(artemis_messages_added{pod=\"$instance\", namespace=\"$namespace\", address!~\"\\\\$.*|activemq\\\\.notifications\"}[1m]) ) )",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Messages Consumed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) ( topk (20, rate(artemis_messages_acknowledged{pod=\"$instance\", namespace=\"$namespace\", address!~\"\\\\$.*|activemq\\\\.notifications\"}[1m]) ) )",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Messages Expired",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) ( topk (20, rate(artemis_messages_expired{pod=\"$instance\", namespace=\"$namespace\"}[1m]) ) )",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Messages to DLQ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) ( topk (20, rate(artemis_messages_killed{pod=\"$instance\", namespace=\"$namespace\"}[1m]) ) )",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (broker) (artemis_disk_store_usage{pod=\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "{{ broker }}"
    }
   ]
  },
  {
   "title": "Paging",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (broker) ( artemis_number_of_pages{pod=\"$instance\", namespace=\"$namespace\"} )",
     "legendFormat": "{{ broker }}"
    },
    {
     "expr": "sum by (address) ( topk (20, artemis_number_of_pages{pod=\"$instance\", namespace=\"$namespace\"} ) )",
     "legendFormat": "{{ address }}"
    }
   ]
  }
 ]
}