apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: users-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: User
  name: user1
---
# This role is needed to create ServiceMonitor. Alternatively if Prometheus operator was installed via OperatorHub on the cluster anywhere, it's part of the default view/edit/admin ClusterRoles already.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit
subjects:
- kind: User
  name: user1