apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # startingCSV: rhsso-operator.7.5.0
# spec:
#   channel: alpha
#   installPlanApproval: Automatic
#   name: keycloak-operator
#   source: community-operators
#   sourceNamespace: openshift-marketplace


