apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sso-1

resources:
- ../../base/grafana

patches:
- target:
    kind: GrafanaDataSource
    name: thanos
  # oc sa get-token grafana-serviceaccount
  patch: |-
    - op: replace
      path: /spec/datasources/0/url
      value: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
    - op: add
      path: /spec/datasources/0/jsonData/customQueryParameters
      value: namespace=sso-1
    - op: replace
      path: /spec/datasources/0/secureJsonData/httpHeaderValue1
      value: Bearer eyJhbGci...