apiVersion: v1
kind: Service
metadata:
  name: http-https-echo
spec:
  selector:
    app: http-https-echo
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443