apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-monitoring

resources:
- namespace.yaml
- operator-group.yaml
- ../../base/grafana/operator
- grafana-cluster-monitoring-view.yaml
