apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-b

resources:
- grafana-rolebinding.yaml
- ../../base/amq/instance
- ../../base/sso/instance
- ../../base/grafana/instance
- ../../base/grafana/dashboards

patches:
- target:
    kind: GrafanaDataSource
    name: thanos
  # oc sa get-token grafana-serviceaccount
  patch: |-
    - op: replace
      path: /spec/datasources/0/url
      value: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
    - op: add
      path: /spec/datasources/0/jsonData/customQueryParameters
      value: namespace=team-b
    - op: replace
      path: /spec/datasources/0/secureJsonData/httpHeaderValue1
      value: Bearer eyJhbGc...
- target:
    kind: Grafana
    name: grafana
  patch: |-
    - op: add
      path: /spec/containers/0/args/-
      value: '-openshift-sar={"resource": "services", "verb": "get", "namespace":"team-b"}'
    - op: add
      path: /spec/containers/0/args/-
      value: '-openshift-delegate-urls={"/": {"resource": "services", "verb": "get", "namespace":"team-b"}}'