{
 "title": "JMX prometheus exporter",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per release > pod",
 "tags": [ "JVM" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(jvm_info,namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(jvm_info{namespace=\"$namespace\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{area=\"heap\",namespace=\"$namespace\",pod=\"$pod\"})*100) / sum(jvm_memory_bytes_max{area=\"heap\",namespace=\"$namespace\",pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{namespace=\"$namespace\",pod=\"$pod\"})*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{namespace=\"$namespace\",pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_info{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Used  {{pod}}"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Max  {{pod}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Used  {{pod}}"
    }
   ]
  },
  {
   "title": "PS Eden Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\",pod=\"$pod\", pool=~\".*Eden Space\"}",
     "legendFormat": "Max  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",pod=\"$pod\", pool=~\".*Eden Space\"}",
     "legendFormat": "Used  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=\"$namespace\",pod=\"$pod\", pool=~\".*Eden Space\"}",
     "legendFormat": "Committed  {{pod}}"
    }
   ]
  },
  {
   "title": "PS Old Gen | Tenured Gen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\",pod=\"$pod\", pool=~\"PS Old Gen|Tenured Gen\"}",
     "legendFormat": "Max  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",pod=\"$pod\", pool=~\"PS Old Gen|Tenured Gen\"}",
     "legendFormat": "Used  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=\"$namespace\",pod=\"$pod\", pool=~\"PS Old Gen|Tenured Gen\"}",
     "legendFormat": "Committed  {{pod}}"
    }
   ]
  },
  {
   "title": "PS Survivor Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\",pod=\"$pod\", pool=~\".*Survivor Space\"}",
     "legendFormat": "Max  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",pod=\"$pod\", pool=~\".*Survivor Space\"}",
     "legendFormat": "Used  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=\"$namespace\",pod=\"$pod\", pool=~\".*Survivor Space\"}",
     "legendFormat": "Committed  {{pod}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\",pod=\"$pod\", pool=\"Metaspace\"}",
     "legendFormat": "Max {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",pod=\"$pod\", pool=\"Metaspace\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=\"$namespace\",pod=\"$pod\", pool=\"Metaspace\"}",
     "legendFormat": "Committed {{pod}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\",pod=\"$pod\", pool=\"Compressed Class Space\"}",
     "legendFormat": "Max {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",pod=\"$pod\", pool=\"Compressed Class Space\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=\"$namespace\",pod=\"$pod\", pool=\"Compressed Class Space\"}",
     "legendFormat": "Committed {{pod}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\",pod=\"$pod\", pool=\"Code Cache\"}",
     "legendFormat": "Max {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",pod=\"$pod\", pool=\"Code Cache\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=\"$namespace\",pod=\"$pod\", pool=\"Code Cache\"}",
     "legendFormat": "Committed {{pod}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "JVM current threads {{pod}}"
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "JVM daemon threads {{pod}}"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "JVM deadlocked threads {{pod}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{gc}} {{pod}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{namespace=\"$namespace\",pod=\"$pod\"}[5m])",
     "legendFormat": "{{gc}} {{pod}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "loaded  {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "CPU {{pod}}"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_errors_total{namespace=\"$namespace\",pod=~\"$pod\"}[2h])) by (pod)",
     "legendFormat": "Transmit {{pod}}"
    },
    {
     "expr": "sum(irate(container_network_receive_errors_total{namespace=\"$namespace\",pod=~\"$pod\"}[2h])) by (pod)",
     "legendFormat": "Receive {{pod}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$pod\"}[2h])) by (pod)",
     "legendFormat": "Transmit  {{pod}}"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$pod\"}[2h])) by (pod)",
     "legendFormat": "Receive  {{pod}}"
    }
   ]
  }
 ]
}