{
 "title": "Keycloak Metrics",
 "description": "Monitoring Keycloak metrics",
 "tags": [ "Keycloak" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(keycloak_request_duration_count,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Heap used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{namespace=\"$namespace\", pod=\"keycloak-0\", area=\"heap\"})*100/sum(jvm_memory_bytes_max{namespace=\"$namespace\", pod=\"keycloak-0\", area=\"heap\"})",
     "legendFormat": "keycloak-0"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{namespace=\"$namespace\", pod=\"keycloak-1\", area=\"heap\"})*100/sum(jvm_memory_bytes_max{namespace=\"$namespace\", pod=\"keycloak-1\", area=\"heap\"})",
     "legendFormat": "keycloak-1"
    }
   ]
  },
  {
   "title": "Pods status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{namespace=\"$namespace\", job=\"keycloak\"})",
     "legendFormat": "Keycloak Instances"
    },
    {
     "expr": "kube_deployment_status_condition{namespace=\"$namespace\", deployment=\"keycloak-postgresql\", status=\"true\", condition=\"Available\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "HTTP Errors count [5m]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(keycloak_response_errors{namespace=\"$namespace\", job=\"keycloak\"}[5m]))"
    }
   ]
  },
  {
   "title": "DB active connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jboss_datasources_pool_active_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JGroups cluster view",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jboss_jgroups_num_members{namespace=\"$namespace\", container=\"keycloak\"}",
     "legendFormat": "{{pod}} view"
    }
   ]
  },
  { "title": "Database and Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Number of database connections in pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jboss_datasources_pool_active_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}) by (pod)",
     "legendFormat": "Active for {{pod}}"
    },
    {
     "expr": "sum(jboss_datasources_pool_available_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}) by (pod)",
     "legendFormat": "Available for {{pod}}"
    }
   ]
  },
  {
   "title": "Number of transactions [5m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jboss_datasources_pool_xacommit_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}[5m])",
     "legendFormat": "Number of commits for {{pod}}"
    },
    {
     "expr": "rate(jboss_datasources_pool_xarollback_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}[5m])",
     "legendFormat": "Number of rollbacks for {{pod}}"
    },
    {
     "expr": "rate(jboss_datasources_pool_blocking_failure_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}[5m])",
     "legendFormat": "Number of failures for {{pod}}"
    }
   ]
  },
  {
   "title": "Number of entries in caches",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jboss_infinispan_number_of_entries{cache=\"actionTokens\", cache_container=\"keycloak\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "actionTokens for {{pod}}"
    },
    {
     "expr": "sum(jboss_infinispan_number_of_entries{cache=\"authenticationSessions\", cache_container=\"keycloak\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "authenticationSessions for {{pod}}"
    },
    {
     "expr": "sum(jboss_infinispan_number_of_entries{cache=\"clientSessions\", cache_container=\"keycloak\", namespace=\"$namespace\"}) by (pod)\r",
     "legendFormat": "clientSessions for {{pod}}"
    },
    {
     "expr": "sum(jboss_infinispan_number_of_entries{cache=\"loginFailures\", cache_container=\"keycloak\", namespace=\"$namespace\"}) by (pod)\r",
     "legendFormat": "loginFailures for {{pod}}"
    },
    {
     "expr": "sum(jboss_infinispan_number_of_entries{cache=\"offlineClientSessions\", cache_container=\"keycloak\", namespace=\"$namespace\"}) by (pod)\r",
     "legendFormat": "offlineClientSessions for {{pod}}"
    },
    {
     "expr": "sum(jboss_infinispan_number_of_entries{cache=\"offlineSessions\", cache_container=\"keycloak\", namespace=\"$namespace\"}) by (pod)\r",
     "legendFormat": "offlineSessions for {{pod}}"
    },
    {
     "expr": "sum(jboss_infinispan_number_of_entries{cache=\"sessions\", cache_container=\"keycloak\", namespace=\"$namespace\"}) by (pod)\r",
     "legendFormat": "sessions for {{pod}}"
    },
    {
     "expr": "sum(jboss_infinispan_number_of_entries{cache=\"work\", cache_container=\"keycloak\", namespace=\"$namespace\"}) by (pod)\r",
     "legendFormat": "work for {{pod}}"
    }
   ]
  },
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "HTTP Requests [5m]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(keycloak_request_duration_count{namespace=\"$namespace\"}[5m])) by (pod, method)\r\n",
     "legendFormat": "{{pod}} {{method}}"
    }
   ]
  },
  {
   "title": "Realm myrealm HTTP endpoints [5m]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(keycloak_request_duration_sum{namespace=\"$namespace\", job=\"keycloak\", resource=~\"realms,realms/myrealm/.+\"}[5m]) /rate(keycloak_request_duration_count{namespace=\"$namespace\", job=\"keycloak\", resource=~\"realms,realms/myrealm/.+\"}[5m])",
     "legendFormat": "{{ pod }} {{method}} {{resource}}"
    }
   ]
  },
  { "title": "Detailed metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", namespace=\"$namespace\", pod=~\"keycloak-.+\"}",
     "legendFormat": "JVM Heap for {{pod}}"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\",namespace=\"$namespace\", pod=~\"keycloak-.+\"}",
     "legendFormat": "Max heap for {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"keycloak-.+\"}",
     "legendFormat": "CPU Limit for {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=~\"keycloak-.+\"}",
     "legendFormat": "CPU Request for {{pod}}"
    },
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"keycloak\", pod=~\"keycloak-.+\"} ",
     "legendFormat": "CPU Load for {{pod}}"
    }
   ]
  },
  {
   "title": "Total GC Time [1m]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{namespace=\"$namespace\",pod=~\"keycloak-.+\"}[1m])",
     "legendFormat": "{{gc}} {{pod}}"
    }
   ]
  },
  {
   "title": "Number of GC Collections [30m]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{namespace=\"$namespace\",pod=~\"keycloak-.+\"}",
     "legendFormat": "{{gc}} {{pod}}"
    }
   ]
  },
  {
   "title": "IO Threads",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\", pod=~\"keycloak-.+\"}",
     "legendFormat": "JVM current threads {{pod}}"
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\", pod=~\"keycloak-.+\"}",
     "legendFormat": "JVM daemon threads {{pod}}"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$namespace\", pod=~\"keycloak-.+\"}",
     "legendFormat": "JVM deadlocked threads {{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=~\"keycloak-.+\"}",
     "legendFormat": "Requests {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"keycloak-.+\"}",
     "legendFormat": "Limits {{pod}}"
    },
    {
     "expr": "container_memory_rss{namespace=\"$namespace\", container=\"keycloak\", pod=~\"keycloak-.+\"}",
     "legendFormat": "RSS for {{pod}}"
    }
   ]
  }
 ]
}